import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import useSWR from 'swr'
import styles from '../styles/Home.module.css'
const fetcher = (...args) => fetch(...args).then(res => res.json())
export default function Home() {
    const [pagenumber, setpagenumber] = useState(1);
  const { data, error } = useSWR(`https://jsonplaceholder.typicode.com/todos/${pagenumber}`, fetcher)
console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        <p>id:{data?.id}</p>
        <p>title:{data?.title}</p>
        <p>Stauts:{data?.completed}</p>
      </div> 
     <button onClick={ ()=>setpagenumber(counter=>counter-1)}>Back Page </button>
     <button onClick={ ()=>setpagenumber(counter=>counter+1)}>Next Page </button>

    </div>
  )
}
